project_name: jarvis

before:
  hooks:

builds:
  - main: ./cmd/jarvis
    env:
      - CGO_ENABLED=0
    goarch: [amd64, arm64]
    goos: [linux, darwin, windows]
    ldflags: -s -w

archives:
  - format: tar.gz
    name_template: >-
      jarvis-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "#86" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: comigor
    name: jarvis-go

dockers:
  - image_templates:
      - "ghcr.io/comigor/jarvis-go:{{ .Tag }}"
      - "ghcr.io/comigor/jarvis-go:v{{ .Major }}"
      - "ghcr.io/comigor/jarvis-go:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
