[package]
name = "jarvis-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
jarvis-web = { path = "../jarvis-web" }
jarvis-core = { path = "../jarvis-core" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
